"""added the orders table

Revision ID: 762bf9929c45
Revises: 888eeee9d41c
Create Date: 2023-03-27 14:46:52.053545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762bf9929c45'
down_revision = '888eeee9d41c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'email')
    op.drop_table('orders')
    # ### end Alembic commands ###
